/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromptGeneratorRouteImport } from './routes/prompt-generator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ImageCombinerRouteImport } from './routes/image-combiner'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const PromptGeneratorRoute = PromptGeneratorRouteImport.update({
  id: '/prompt-generator',
  path: '/prompt-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCombinerRoute = ImageCombinerRouteImport.update({
  id: '/image-combiner',
  path: '/image-combiner',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/image-combiner': typeof ImageCombinerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/prompt-generator': typeof PromptGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/image-combiner': typeof ImageCombinerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/prompt-generator': typeof PromptGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/image-combiner': typeof ImageCombinerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/prompt-generator': typeof PromptGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/image-combiner'
    | '/sitemap.xml'
    | '/prompt-generator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/image-combiner' | '/sitemap.xml' | '/prompt-generator'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/image-combiner'
    | '/sitemap.xml'
    | '/prompt-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ImageCombinerRoute: typeof ImageCombinerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PromptGeneratorRoute: typeof PromptGeneratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prompt-generator': {
      id: '/prompt-generator'
      path: '/prompt-generator'
      fullPath: '/prompt-generator'
      preLoaderRoute: typeof PromptGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-combiner': {
      id: '/image-combiner'
      path: '/image-combiner'
      fullPath: '/image-combiner'
      preLoaderRoute: typeof ImageCombinerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ImageCombinerRoute: ImageCombinerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PromptGeneratorRoute: PromptGeneratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
